// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdasoIdentityServer.Database.Models;

public partial class PersonelTitle
{
    public int Id { get; set; }

    public string Title { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}