// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADASOIdentityServer.Database.Models;

public partial class ProjectRole
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Explanation { get; set; }

    public virtual ICollection<UserProjectRole> UserProjectRole { get; set; } = new List<UserProjectRole>();
}