// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADASOIdentityServer.Database.Models;

public partial class SystemClients
{
    public int Id { get; set; }

    public string ClientId { get; set; }

    public bool? RequirePkce { get; set; }

    public string ClientName { get; set; }

    public string ClientSecrets { get; set; }

    public string AllowedGrantTypes { get; set; }

    public string AllowedGrantTypeExplanation { get; set; }

    public string RedirectUris { get; set; }

    public string PostLogoutRedirectUris { get; set; }

    public int? AccessTokenLifetime { get; set; }

    public bool? AllowOfflineAccess { get; set; }

    public int? RefreshTokenUsage { get; set; }

    public string RefreshTokenUsageExplanation { get; set; }

    public int? RefreshTokenExpiration { get; set; }

    public string RefreshTokenExpirationExplanation { get; set; }

    public int? AbsoluteRefreshTokenLifetime { get; set; }

    public bool? RequireConsent { get; set; }

    public virtual ICollection<SystemClientAllowedScopes> SystemClientAllowedScopes { get; set; } = new List<SystemClientAllowedScopes>();
}