// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADASOIdentityServer.Database.Models;

public partial class SystemApis
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Explanation { get; set; }

    public string SystemName { get; set; }

    public string ApiSecrets { get; set; }

    public virtual ICollection<SystemApiResources> SystemApiResources { get; set; } = new List<SystemApiResources>();
}