// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADASOIdentityServer.Database.Models;

public partial class SystemIdentityRosources
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Explanation { get; set; }

    public string UserClaims { get; set; }
}