// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ADASOIdentityServer.Database.Partial;
using System;
using System.Collections.Generic;

namespace ADASOIdentityServer.Database.Models;

public partial class UserProjectRole
{
    public int Id { get; set; }

    public int ProjectRoleId { get; set; }

    public int UserProjectsId { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Explanation { get; set; }

    public virtual UserProjects UserProjects { get; set; }
}