// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ADASOIdentityServer.Database.Partial;

namespace ADASOIdentityServer.Database.Models;

public partial class UserProjects : UserProjectDto
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? ProjectId { get; set; }

    public virtual Projects Project { get; set; }

    public virtual Users User { get; set; }

    public virtual ICollection<UserProjectRole> UserProjectRole { get; set; } = new List<UserProjectRole>();
}