// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADASOIdentityServer.Database.Models;

public partial class Users
{
    public int Id { get; set; }
    public int RoleId { get; set; }
    public int PersonelTitleId { get; set; }
    public int DepartmentId { get; set; }
    public int ConsultantId { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Email { get; set; }

    public string Password { get; set; }

    public bool? EmailConfirmed { get; set; }

    public string EmailConfirmationCode { get; set; }

    public DateTime? EmailConfirmationExpiry { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string Avatar { get; set; }

    public string TobbUyelikOid { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual Department Department { get; set; }

    public virtual PersonelTitle PersonelTitle { get; set; }

    public virtual Roles Role { get; set; }

    public virtual ICollection<UserProjects> UserProjects { get; set; } = new List<UserProjects>();
}