// <auto-generated> This file follows the database-first model conventions. </auto-generated>
#nullable disable

namespace ADASOIdentityServer.Database.Models;

public partial class UserType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}
