// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UdemyIdentityServer.Database.Models;

public partial class Department
{
    public int Id { get; set; }

    public string Department1 { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}