// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UdemyIdentityServer.Database.Models;

public partial class PersonelTitle
{
    public int Id { get; set; }

    public string Title { get; set; }
}