// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UdemyIdentityServer.Database.Models;

public partial class SystemApiResources
{
    public int Id { get; set; }

    public int? SystemApiId { get; set; }

    public string ApiResource { get; set; }

    public string ApiFunction { get; set; }

    public string Explanation { get; set; }

    public virtual SystemApis SystemApi { get; set; }
}