// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UdemyIdentityServer.Database.Models;

public partial class SystemClientAllowedScopes
{
    public int Id { get; set; }

    public int? SystemClientId { get; set; }

    public string Name { get; set; }

    public string Explanation { get; set; }

    public virtual SystemClients SystemClient { get; set; }
}