// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UdemyIdentityServer.Database.Models;

public partial class SystemApiScopes
{
    public int Id { get; set; }

    public string ApiResource { get; set; }

    public string Scope { get; set; }

    public string Explanation { get; set; }
}