// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UdemyIdentityServer.Database.Models;

public partial class Users
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string Avatar { get; set; }

    public string PersonnelTitle { get; set; }

    public string PersonnelDepartmen { get; set; }

    public string PersonnelConsultant { get; set; }

    public string TobbUyelikOid { get; set; }

    public virtual Roles Role { get; set; }
}